
server:
   port: 8096
   graphql:
     graphiql:
       enabled: true
       path:
         /graphiql:

spring:
  application:
     name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservicedb
   #url: jdbc:mysql://localhost:3306/microservicedb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/inventory-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: inventory-client
      principle-attribute: preferred_username