
server:
  port: 8090
  graphql:
    graphiql:
      enabled: true
      path:
        /graphiql:

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservicedb
    #url: jdbc:mysql://localhost:3306/microservicedb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
